name: build-deploy-with-preview

on:
  # push:
  #   branches: ["master", "preview"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: master
      - name: Checkout preview branch
        uses: actions/checkout@v3
        with:
          ref: preview
          path: preview
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build master with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./master
          destination: ./_site
      - name: Build preview with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./preview
          destination: ./_site/_preview
      - name: Sanity check
        run: |
          ls ./_site
          ls ./_site/_preview
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1

  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1